# Generated by Django 5.2.7 on 2025-12-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('J', 'Jurídico'), ('V', 'Natural'), ('E', 'Extranjero')], max_length=1)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
