# Generated by Django 5.2.7 on 2025-12-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='objeto',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='contrato',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_servicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='ventas.contrato'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='PartidaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='ventas.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.cotizacion')),
                ('partida_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.partidacontrato')),
            ],
        ),
    ]
