# Generated by Django 5.2.7 on 2026-05-01 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Rol"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password_min_length",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Longitud mínima de contraseña"
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Tiempo de sesión (minutos)"
                    ),
                ),
                (
                    "max_login_attempts",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Máximo de intentos de login"
                    ),
                ),
                (
                    "password_expiry_days",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Expiración de contraseña (días)"
                    ),
                ),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=False,
                        verbose_name="Requiere autenticación de dos factores",
                    ),
                ),
                (
                    "audit_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Auditoría habilitada"
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Política de Seguridad",
                "verbose_name_plural": "Políticas de Seguridad",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de sesión"),
                            ("logout", "Cierre de sesión"),
                            ("create", "Creación"),
                            ("update", "Actualización"),
                            ("delete", "Eliminación"),
                            ("approve", "Aprobación"),
                            ("export", "Exportación"),
                            ("access_denied", "Acceso denegado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("modulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora",
                "verbose_name_plural": "Bitácoras",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("core", "Core"),
                            ("compras", "Compras"),
                            ("ventas", "Ventas"),
                            ("contabilidad", "Contabilidad"),
                            ("tesoreria", "Tesorería"),
                            ("rrhh", "Recursos Humanos"),
                            ("nomina", "Nómina"),
                            ("configuracion", "Configuración"),
                        ],
                        max_length=50,
                    ),
                ),
                ("puede_ver", models.BooleanField(default=False)),
                ("puede_crear", models.BooleanField(default=False)),
                ("puede_editar", models.BooleanField(default=False)),
                ("puede_eliminar", models.BooleanField(default=False)),
                ("puede_aprobar", models.BooleanField(default=False)),
                ("puede_exportar", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permisos",
                        to="configuracion.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de Módulo",
                "verbose_name_plural": "Permisos de Módulos",
                "ordering": ["modulo"],
                "unique_together": {("role", "modulo")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="configuracion.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol de Usuario",
                "verbose_name_plural": "Roles de Usuarios",
                "unique_together": {("user", "role")},
            },
        ),
    ]
