# Generated by Django 5.2.7 on 2026-05-01 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Asiento"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "total_debe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_haber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "verbose_name": "Asiento Contable",
                "verbose_name_plural": "Asientos Contables",
                "ordering": ["-fecha", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="ParametrosContables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=60, unique=True)),
                ("valor", models.CharField(blank=True, max_length=200, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CuentaContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("PASIVO", "Pasivo"),
                            ("PATRIMONIO", "Patrimonio"),
                            ("INGRESO", "Ingreso"),
                            ("COSTO", "Costo"),
                            ("GASTO", "Gasto"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
                (
                    "naturaleza",
                    models.CharField(
                        choices=[("D", "Deudora"), ("A", "Acreedora")],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("nivel", models.PositiveSmallIntegerField(default=1)),
                ("es_activo", models.BooleanField(default=True)),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hijas",
                        to="contabilidad.cuentacontable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Cuentas Contables",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "debe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "haber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "asiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="contabilidad.asientocontable",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contabilidad.cuentacontable",
                        verbose_name="Cuenta Contable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento Contable",
                "verbose_name_plural": "Movimientos Contables",
                "ordering": ["id"],
            },
        ),
    ]
