"""
Django settings for perforosven project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# ============================================================
# 🔹 RUTAS PRINCIPALES
# ============================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# 🔹 CONFIGURACIÓN BÁSICA
# ============================================================
SECRET_KEY = 'django-insecure-th$kl$or#t73%n&v2dekg3m1r9$qkaejx(=q%%sry9wpzkvf)7'  # cámbiala en producción
DEBUG = True
ALLOWED_HOSTS = []  # agrega tu IP o dominio cuando despliegues

# ============================================================
# 🔹 APLICACIONES INSTALADAS
# ============================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',       # 🔹 Dashboard general
    'compras',    # 🔹 Módulo de compras
    'contabilidad', # 🔹 Módulo de contabilidad
    'ventas',    # 🔹 Módulo de ventas
    'rest_framework',  # 🔹 DRF para APIs

]

# ============================================================
# 🔹 MIDDLEWARE
# ============================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================
# 🔹 URLS Y WSGI
# ============================================================
ROOT_URLCONF = 'perforosven.urls'
WSGI_APPLICATION = 'perforosven.wsgi.application'

# ============================================================
# 🔹 TEMPLATES
# ============================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Carpeta global donde está base.html
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,  # Permite que Django busque templates dentro de las apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ============================================================
# 🔹 BASE DE DATOS (PostgreSQL)
# ============================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'perforosven_db',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# ============================================================
# 🔹 VALIDADORES DE CONTRASEÑAS
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================================
# 🔹 INTERNACIONALIZACIÓN
# ============================================================
LANGUAGE_CODE = 'es-ve'
TIME_ZONE = 'America/Caracas'
USE_I18N = True
USE_TZ = True

# ============================================================
# 🔹 ARCHIVOS ESTÁTICOS Y MEDIA
# ============================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Ruta global de recursos (css, js, img)
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Para producción

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================
# 🔹 CONFIGURACIÓN FINAL
# ============================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# 🔹 OPCIONAL: CONFIGURACIÓN DE LOGIN (para cuando agreguemos autenticación)
# ============================================================
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'