# Generated by Django 5.2.7 on 2026-04-30 19:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_oc",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Orden de Compra",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("descripcion", models.CharField(max_length=200)),
                ("unidad_medida", models.CharField(max_length=20)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["descripcion"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_proveedor",
                    models.CharField(default="P0001", max_length=20, unique=True),
                ),
                (
                    "rif",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[JGVEP]-\\d{8}-\\d$",
                                "Formato inválido. Ej: J-12345678-9",
                            )
                        ],
                        verbose_name="RIF",
                    ),
                ),
                (
                    "nombre_empresa",
                    models.CharField(
                        max_length=255, verbose_name="Nombre o Razón Social"
                    ),
                ),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "correo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "representante_nombre",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre del Representante",
                    ),
                ),
                (
                    "representante_cedula",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Cédula del Representante",
                    ),
                ),
                (
                    "representante_telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono del Representante",
                    ),
                ),
                (
                    "representante_correo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo del Representante",
                    ),
                ),
                (
                    "banco_nacional",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Banco Nacional",
                    ),
                ),
                (
                    "cuenta_nacional",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Cuenta Nacional",
                    ),
                ),
                (
                    "tipo_cuenta_nacional",
                    models.CharField(
                        blank=True,
                        choices=[("corriente", "Corriente"), ("ahorro", "Ahorro")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "banco_extranjero",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Banco Extranjero",
                    ),
                ),
                (
                    "cuenta_extranjera",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Cuenta Extranjera",
                    ),
                ),
                (
                    "swift",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código SWIFT",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["nombre_empresa"],
            },
        ),
        migrations.CreateModel(
            name="DetalleOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="compras.ordencompra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compras.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Orden",
                "verbose_name_plural": "Detalles de Órdenes",
            },
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="compras.proveedor"
            ),
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_factura", models.DateField()),
                (
                    "fecha_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("descripcion_servicio", models.TextField()),
                ("numero_factura", models.CharField(max_length=50, unique=True)),
                (
                    "numero_control",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("soporte_documento", models.TextField(blank=True, null=True)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("USD", "Dólares (USD)"), ("VES", "Bolívares (VES)")],
                        default="VES",
                        max_length=3,
                    ),
                ),
                (
                    "monto_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_factura",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("municipio", models.CharField(max_length=100)),
                (
                    "ret_iva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "ret_islr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "tasa_cambio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=10
                    ),
                ),
                ("tiene_iva", models.BooleanField(default=False)),
                (
                    "alicuota_iva",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "porcentaje_ret_municipal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Porcentaje Retención Municipal (%)",
                    ),
                ),
                (
                    "ret_municipal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Monto Retención Municipal",
                    ),
                ),
                (
                    "orden_compra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compras.ordencompra",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="compras.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_factura"],
            },
        ),
    ]
