# Generated by Django 5.2.7 on 2025-11-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_ordencompra_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='numero_oc',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Orden de Compra'),
        ),
    ]
