# Generated by Django 5.2.7 on 2025-11-04 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_ordencompra_numero_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='banco_extranjero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco Extranjero'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco_nacional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco Nacional'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_proveedor',
            field=models.CharField(default='P0001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_extranjera',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cuenta Extranjera'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_nacional',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cuenta Nacional'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='representante_cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del Representante'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='representante_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Representante'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='representante_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Representante'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='representante_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Representante'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='swift',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código SWIFT'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_cuenta_nacional',
            field=models.CharField(blank=True, choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro')], max_length=20, null=True, verbose_name='Tipo de Cuenta Nacional'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_empresa',
            field=models.CharField(max_length=255, verbose_name='Nombre o Razón Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rif',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[JGVEP]-\\d{8}-\\d$', 'Formato inválido. Ej: J-12345678-9')], verbose_name='RIF'),
        ),
    ]
