# Generated by Django 5.2.7 on 2025-11-05 01:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_proveedor_banco_extranjero_proveedor_banco_nacional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion_servicio', models.TextField()),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('numero_control', models.CharField(max_length=50)),
                ('soporte_documento', models.TextField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], default='VES', max_length=3)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('municipio', models.CharField(max_length=100)),
                ('ret_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ret_islr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('monto_bs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='compras.proveedor')),
            ],
        ),
    ]
