# Generated by Django 5.2.7 on 2025-11-05 02:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_facturacompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion_servicio', models.TextField()),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('numero_control', models.CharField(blank=True, max_length=50, null=True)),
                ('soporte_documento', models.TextField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('VES', 'Bolívares (VES)')], default='VES', max_length=3)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_factura', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('municipio', models.CharField(max_length=100)),
                ('ret_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ret_islr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tasa_cambio', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
        ),
        migrations.DeleteModel(
            name='FacturaCompra',
        ),
    ]
