# Generated by Django 5.2.7 on 2025-11-14 03:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_factura_delete_facturacompra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha_factura'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AddField(
            model_name='factura',
            name='porcentaje_ret_municipal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje Retención Municipal (%)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='ret_municipal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Retención Municipal'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_cuenta_nacional',
            field=models.CharField(blank=True, choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro')], max_length=20, null=True),
        ),
    ]
