# Generated by Django 5.2.7 on 2025-11-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_factura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='alicuota_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tiene_iva',
            field=models.BooleanField(default=False),
        ),
    ]
