"""
Django settings for perforosven project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import environ

# ============================================================
# 🔹 INICIALIZAR ENVIRON
# ============================================================
env = environ.Env(
    DEBUG=(bool, False)
)

# ============================================================
# 🔹 RUTA BASE DEL PROYECTO
# ============================================================
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ============================================================
# 🔹 LEER VARIABLES DE ENTORNO
# ============================================================
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# ============================================================
# 🔹 CONFIGURACIÓN BÁSICA
# ============================================================
SECRET_KEY = env('DJANGO_SECRET_KEY')
DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])

# ============================================================
# 🔹 APLICACIONES INSTALADAS
# ============================================================
INSTALLED_APPS = [
    # Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps del proyecto
    'core',
    'accounts',
    'compras',
    'contabilidad',
    'ventas',

    # Terceros
    'rest_framework',
]

# ============================================================
# 🔹 MODELO PERSONALIZADO DE USUARIO (CRÍTICO)
# ============================================================
AUTH_USER_MODEL = 'accounts.CustomUser'

# ============================================================
# 🔹 MIDDLEWARE
# ============================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Middleware personalizado
    'core.middleware.LoginRequiredMiddleware',
]

# ============================================================
# 🔹 SEGURIDAD DE SESIONES
# ============================================================
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# Cambiar a True en producción con HTTPS
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

# Seguridad adicional
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# ============================================================
# 🔹 URLS Y WSGI
# ============================================================
ROOT_URLCONF = 'perforosven.urls'
WSGI_APPLICATION = 'perforosven.wsgi.application'

# ============================================================
# 🔹 TEMPLATES
# ============================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Templates globales
        'DIRS': [BASE_DIR / 'templates'],

        # Templates dentro de apps
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ============================================================
# 🔹 BASE DE DATOS (POSTGRESQL)
# ============================================================
DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'CONN_MAX_AGE': 60,
    }
}

# ============================================================
# 🔹 VALIDADORES DE CONTRASEÑA
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================================
# 🔹 DJANGO REST FRAMEWORK
# ============================================================
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# ============================================================
# 🔹 INTERNACIONALIZACIÓN
# ============================================================
LANGUAGE_CODE = 'es-ve'
TIME_ZONE = 'America/Caracas'

USE_I18N = True
USE_TZ = True

# ============================================================
# 🔹 ARCHIVOS ESTÁTICOS
# ============================================================
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# ============================================================
# 🔹 ARCHIVOS MEDIA
# ============================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================
# 🔹 CONFIGURACIÓN LOGIN / LOGOUT
# ============================================================
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:inicio'
LOGOUT_REDIRECT_URL = 'accounts:login'

# ============================================================
# 🔹 CONFIGURACIÓN POR DEFECTO
# ============================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'